var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/live/[roomId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__aa629d71._.js")
R.c("server/chunks/ssr/workspace_projects_4db297ae._.js")
R.c("server/chunks/ssr/workspace_projects_80316702._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0f94b15c._.js")
R.c("server/chunks/ssr/86bb5__pnpm_097a8a9e._.js")
R.c("server/chunks/ssr/5a353_next_dist_1c954b34._.js")
R.c("server/chunks/ssr/workspace_projects_src_app_71a1aa31._.js")
R.c("server/chunks/ssr/5a353_next_dist_client_components_builtin_global-error_9226e0fe.js")
R.c("server/chunks/ssr/workspace_projects_src_e7e167e8._.js")
R.c("server/chunks/ssr/5a353_next_dist_client_components_964288bc._.js")
R.c("server/chunks/ssr/5a353_next_dist_client_components_builtin_forbidden_581146b8.js")
R.c("server/chunks/ssr/5a353_next_dist_client_components_builtin_unauthorized_c4e56f67.js")
R.c("server/chunks/ssr/workspace_projects__next-internal_server_app_live_[roomId]_page_actions_7ea5d28a.js")
R.m(17759)
module.exports=R.m(17759).exports
