var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__20e6b432._.js")
R.c("server/chunks/ssr/workspace_projects_4db297ae._.js")
R.c("server/chunks/ssr/5a353_next_dist_esm_build_templates_app-page_ab78569c.js")
R.c("server/chunks/ssr/[root-of-the-server]__c68e9ede._.js")
R.c("server/chunks/ssr/86bb5__pnpm_097a8a9e._.js")
R.c("server/chunks/ssr/5a353_next_dist_1c954b34._.js")
R.c("server/chunks/ssr/workspace_projects_src_app_71a1aa31._.js")
R.c("server/chunks/ssr/workspace_projects_src_e7e167e8._.js")
R.c("server/chunks/ssr/5a353_next_dist_client_components_964288bc._.js")
R.c("server/chunks/ssr/5a353_next_dist_client_components_builtin_forbidden_581146b8.js")
R.c("server/chunks/ssr/workspace_projects__next-internal_server_app__not-found_page_actions_f8eae23d.js")
R.m(12651)
module.exports=R.m(12651).exports
